# Generated by Django 5.0.1 on 2024-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loluser',
            name='accountId',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='loluser',
            name='profileIconId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loluser',
            name='summonerLevel',
            field=models.IntegerField(default=0),
        ),
    ]
