# Generated by Django 5.0.1 on 2024-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0002_loluser_accountid_loluser_profileiconid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loluser',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loluser',
            name='profileIconId',
        ),
        migrations.AddField(
            model_name='loluser',
            name='lossesFlex',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='lossesSolo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='lossesTFT',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='pdlRankedFlex',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='pdlRankedSolo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='pdlTFT',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='profileIconUrl',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='loluser',
            name='rankRankedFlex',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='rankRankedSolo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='rankTFT',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='tierRankedFlex',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='tierRankedSolo',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='tierTFT',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='winsFlex',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='winsSolo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='loluser',
            name='winsTFT',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
