# Generated by Django 5.0.1 on 2024-05-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0003_rename_created_at_loluser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamousTwitchPlayersLol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('puuid', models.CharField(max_length=1000)),
                ('profileIconUrl', models.CharField(max_length=1000)),
                ('channelId', models.CharField(max_length=500)),
            ],
        ),
    ]
