# Generated by Django 5.0.1 on 2024-05-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0004_famoustwitchplayerslol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famoustwitchplayerslol',
            name='profileIconUrl',
        ),
    ]
