# Generated by Django 5.0.1 on 2024-05-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0005_remove_famoustwitchplayerslol_profileiconurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='famoustwitchplayerslol',
            name='region',
            field=models.CharField(default='BR', max_length=100),
        ),
    ]
