# Generated by Django 5.0.1 on 2024-05-13 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0006_famoustwitchplayerslol_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=400)),
                ('tier', models.CharField(max_length=100)),
                ('pdl', models.IntegerField(default=0)),
                ('thumbUrl', models.CharField(max_length=1400)),
                ('started_at', models.DateTimeField()),
                ('FamousTwitchPlayersLol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='famousTwitchPlayersLol', to='leagueoflegends.famoustwitchplayerslol')),
            ],
        ),
    ]
