# Generated by Django 5.0.1 on 2024-05-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0007_playersonline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playersonline',
            old_name='FamousTwitchPlayersLol',
            new_name='famousTwitchPlayersLol',
        ),
    ]
