# Generated by Django 5.0.1 on 2024-05-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0008_rename_famoustwitchplayerslol_playersonline_famoustwitchplayerslol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LolUser',
        ),
    ]
