# Generated by Django 5.0.1 on 2024-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0010_streamertwitchplayerslol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamertwitchplayerslol',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
