# Generated by Django 5.0.1 on 2024-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0011_alter_streamertwitchplayerslol_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamertwitchplayerslol',
            name='thumbUrl',
            field=models.CharField(blank=True, default='', max_length=1400, null=True),
        ),
    ]
