# Generated by Django 5.0.1 on 2024-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueoflegends', '0012_alter_streamertwitchplayerslol_thumburl'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamertwitchplayerslol',
            name='gameNickName',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='streamertwitchplayerslol',
            name='gameTag',
            field=models.CharField(default='', max_length=12),
        ),
    ]
